### ISSUE TITLE
(BUG Logger VERSION 1.0 ) The application crashes when I click on the Hello option two to three times.

### ISSUE THREAD

**Issue by friendsmobile** [amuyu/Logger#2]
# Project Information

* Repository:  https://github.com/amuyu/Logger
* Project Name:  Logger
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/amuyu/Logger/releases

# Expected behavior

When I click on the Hello option two to three times, the application should not crash but the option in this button should appear.

# Actual behavior

The application crashes when I click on the Hello option two to three times.

#### How to reproduce

* [Download ](https://github.com/amuyu/Logger/releases)the application
*  open the application
*  click on the Hello option two to three times.
* Note the Error

* Browser/App version:  1.0
* Operating system: 6.0

#### Recording Of The Bug

![20190725_150721](https://user-images.githubusercontent.com/51118734/61866228-a5fbb580-ae89-11e9-8c2b-a43e13a5de70.gif)

#### Logcat

<pre><code>E/AndroidRuntime(12736): FATAL EXCEPTION: main

E/AndroidRuntime(12736): Process: com.amuyu.logger.sample, PID: 12736

E/AndroidRuntime(12736): java.lang.IllegalThreadStateException: Thread already started

E/AndroidRuntime(12736): 	at java.lang.Thread.checkNotStarted(Thread.java:849)

E/AndroidRuntime(12736): 	at java.lang.Thread.start(Thread.java:1059)

E/AndroidRuntime(12736): 	at com.amuyu.logger.sample.ui.DemoActivity.greetingClicked(DemoActivity.java:41)

E/AndroidRuntime(12736): 	at com.amuyu.logger.sample.ui.DemoActivity$$ViewBinder$1.doClick(DemoActivity$$ViewBinder.java:17)

E/AndroidRuntime(12736): 	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)

E/AndroidRuntime(12736): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(12736): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(12736): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(12736): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(12736): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(12736): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(12736): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(12736): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(12736): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(12736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by amuyu** [comment]
Please use version 1.1.6 because an error occurs in version 1.1.5.

**Comment by friendsmobile** [comment]
ok

**Comment by friendsmobile** [comment]
the bug has been fixed in 1.1.6 version thanks u
